version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - staticcheck
    - govet
    - errcheck
    - ineffassign
    - unused
    - misspell

formatters:
  enable:
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
