# GoTyper Configuration File
# Place this file as .gotyper.yml in your project root or home directory

# Default package name for generated structs
package: "models"

# Default root struct name when not specified
root_name: "ApiResponse"

# Code formatting options
formatting:
  enabled: true
  # Use gofumpt for stricter formatting (requires gofumpt installed)
  use_gofumpt: false

# Type inference settings
types:
  # Prefer int64 over int for all integers (safer for large numbers)
  force_int64: false
  
  # Always use pointers for optional fields (fields that can be null/missing)
  optional_as_pointers: true
  
  # Custom type mappings for specific patterns
  mappings:
    # Map fields containing "id" to specific types
    - pattern: ".*_id$|^id$"
      type: "int64"
      comment: "Primary/Foreign key IDs"
    
    # Map email fields to custom Email type
    - pattern: ".*email.*"
      type: "string"
      import: "github.com/yourorg/types"
      comment: "Email address"
    
    # Map timestamp fields to time.Time
    - pattern: ".*_at$|.*_time$|timestamp"
      type: "time.Time"
      import: "time"
      comment: "Timestamp field"
    
    # Map UUID fields
    - pattern: ".*uuid.*|.*guid.*"
      type: "uuid.UUID"
      import: "github.com/google/uuid"
      comment: "UUID field"

# Field naming conventions
naming:
  # Convert snake_case JSON keys to PascalCase Go field names
  pascal_case_fields: true

  # Custom field name mappings (takes precedence over pascal_case_fields)
  field_mappings:
    "user_id": "UserID"
    "api_key": "APIKey"
    "url": "URL"
    "http_status": "HTTPStatus"
    "oauth_token": "OAuthToken"

  # Custom plural to singular mappings for array element naming
  # Use this for domain-specific terms not in the built-in dictionary
  custom_singulars:
    "datums": "datum"        # Scientific term
    "formulae": "formula"    # Latin plural
    "stimuli": "stimulus"    # Psychology/biology term
    "alumni": "alumnus"      # Academic term

# JSON tag generation
json_tags:
  # Include omitempty for pointer fields
  omitempty_for_pointers: true
  
  # Include omitempty for slice fields
  omitempty_for_slices: true
  
  # Additional tags to include (json is always included)
  additional_tags:
    - "yaml"
    - "xml"

# Validation tag generation
validation:
  enabled: false
  # Generate validation tags based on field patterns
  rules:
    - pattern: ".*email.*"
      tag: "validate:\"required,email\""
    
    - pattern: ".*_id$|^id$"
      tag: "validate:\"required,min=1\""
    
    - pattern: ".*password.*"
      tag: "validate:\"required,min=8\""

# Output options
output:
  # Add file header comment (supports template variables)
  file_header: |
    // Code generated by GoTyper. DO NOT EDIT.
    // Source: {{ .source_file }}
    // Generated: {{ .timestamp }}
  
  # Generate constructor functions
  generate_constructors: false
  
  # Generate String() methods for structs
  generate_string_methods: false

# Array handling
arrays:
  # When array elements have different fields, create merged struct
  merge_different_objects: true
  
  # Singularize array element type names (users -> User)
  singularize_names: true

# Development options
dev:
  # Enable debug output
  debug: false
  
  # Verbose logging
  verbose: false