version: "3.5"

services:
  golangci-lint:
    image: golangci/golangci-lint:v2.3.0
    working_dir: /app
    volumes:
      - ..:/app
      - ~/.cache/golangci-lint/v1.54.1:/root/.cache
  
  goreleaser:
    image: goreleaser/goreleaser:v2.11.2
    environment:
      - BUILDKITE_AGENT_JOB_API_SOCKET
      - BUILDKITE_AGENT_JOB_API_TOKEN
      - GITHUB_TOKEN
    working_dir: /app
    volumes:
      - ..:/app
      - ${BUILDKITE_AGENT_JOB_API_SOCKET}:${BUILDKITE_AGENT_JOB_API_SOCKET}
  
  golang:
    image: golang:1.25
    working_dir: /app
    volumes:
      - ..:/app
