agents:
  queue: "default"

steps:
  - group: "Set up :go:"
    key: "setup"
    steps:
      - label: ":go: Build"
        plugins:
          - docker-compose#v5.10.0:
              config: .buildkite/compose.yml
              run: golang
              command: ["go", "build", "-v", "./..."]

      - label: ":test_tube: Test"
        plugins:
          - docker-compose#v5.10.0:
              config: .buildkite/compose.yml
              run: golang
              command: ["go", "test", "-v", "./..."]

      - label: ":mag: Vet"
        plugins:
          - docker-compose#v5.10.0:
              config: .buildkite/compose.yml
              run: golang
              command: ["go", "vet", "./..."]

      - label: ":lint-roller: Lint"
        plugins:
          - docker-compose#v5.10.0:
              config: .buildkite/compose.yml
              run: golangci-lint
              command: ["golangci-lint", "run", "--timeout=5m"]
              tty: true

      - label: ":matrix: Test Matrix"
        command: ".buildkite/scripts/test-matrix | buildkite-agent pipeline upload"

  - block: ":rocket: Release"
    key: "release"
    depends_on: "setup"
    prompt: "Choose a tag for this release"
    fields:
      - text: "Release Tag"
        key: "release-tag"
        hint: "e.g., v1.0.0"
        required: true

  - label: ":git: Create Tag"
    command: ".buildkite/scripts/tag"
    key: "create-tag"
    depends_on: "release"

  - label: ":goreleaser: Release"
    plugins:
      - docker-compose#v5.10.0:
          config: .buildkite/compose.yml
          run: goreleaser
          command: ["release", "--clean"]
          env:
            - GITHUB_TOKEN
    depends_on: "create-tag"
