name: Bug Report
description: File a bug report to help us improve GoTyper
title: "[Bug]: "
labels: ["bug", "needs-triage"]
projects: ["mcncl/1"]
assignees:
  - mcncl
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: GoTyper Version
      description: What version of GoTyper are you running?
      placeholder: e.g., v1.2.3 or commit hash
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go are you using?
      placeholder: e.g., go1.25.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., macOS 14.1, Ubuntu 22.04, Windows 11
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: GoTyper should generate...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened? Include any error messages.
      placeholder: Instead, GoTyper...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Create a JSON file with...
        2. Run `gotyper -i file.json`
        3. See error...
    validations:
      required: true

  - type: textarea
    id: sample-json
    attributes:
      label: Sample JSON (if applicable)
      description: Please provide the JSON input that causes the issue
      render: json
      placeholder: |
        {
          "field": "value"
        }

  - type: textarea
    id: config-file
    attributes:
      label: Configuration File (if applicable)
      description: Please provide your .gotyper.yml configuration if relevant
      render: yaml
      placeholder: |
        package: "models"
        types:
          unix_timestamps_as_time: true

  - type: textarea
    id: command-used
    attributes:
      label: Command Used
      description: What exact command did you run?
      render: bash
      placeholder: gotyper -i input.json -p mypackage -c config.yml

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: This started happening after...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues that describe this problem
          required: true
        - label: I have tried with the latest version of GoTyper
          required: true
        - label: I have provided all the requested information above
          required: true