name: Feature Request
description: Suggest an idea for GoTyper
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
projects: ["mcncl/1"]
assignees:
  - mcncl
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feature suggestion! Please provide as much detail as possible.

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like GoTyper to...
    validations:
      required: true

  - type: textarea
    id: example-usage
    attributes:
      label: Example Usage
      description: Show how this feature would be used
      placeholder: |
        # Example command:
        gotyper --new-feature input.json
        
        # Expected output:
        ...
    validations:
      required: true

  - type: textarea
    id: sample-input-output
    attributes:
      label: Sample Input/Output (if applicable)
      description: Provide examples of input JSON and expected Go output
      render: json
      placeholder: |
        Input JSON:
        {
          "timestamp": 1674641400
        }
        
        Expected Go struct:
        type Example struct {
          Timestamp time.Time `json:"timestamp"`
        }

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Type Detection
        - Tag Generation
        - Configuration
        - CLI Interface
        - Performance
        - Output Formatting
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: I've tried using... but it doesn't...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: This would be particularly useful for...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests that describe this idea
          required: true
        - label: I have checked that this isn't already implemented in the latest version
          required: true
        - label: I understand this is a suggestion and may not be implemented
          required: true