#!/bin/env bash

#
# This script runs goreleaser to create a release using docker-compose
#

set -euo pipefail

TAG="$(buildkite-agent meta-data get "release-tag")"

echo "+++ Running GoReleaser for tag ${TAG}"
docker-compose -f .buildkite/docker-compose.yml run --rm goreleaser release --clean

echo "Release completed successfully! 🎉"
